BinarySearchTree: BinaryNode.o BinarySearchTree.o main.o
			g++ BinaryNode.o BinarySearchTree.o main.o -o BinarySearchTree

BinaryNode.o : BinaryNode.cpp
		g++ -c BinaryNode.cpp

BinarySearchTree.o : BinarySearchTree.cpp
		g++ -c BinarySearchTree.cpp

main.o : main.cpp
		g++ -c main.cpp
